### ISSUE TITLE
Proj is failing to create a Transformer object for the vertical transformation from N2000 height to EVRF2019 height (1) (EPSG:9573).

### ISSUE THREAD

**Issue by phaarnes** [OSGeo/proj.4#4342]
#### Ex. 1 Create  a instance of the ``Transformer`` class by using OGC WKT 2 (WKT 2019)

```python
from pyproj import Transformer

wkt_9573 = 'COORDINATEOPERATION["N2000 height to EVRF2019 height (1)",VERSION["EuG-Fin 2019z 2020-09"],SOURCECRS[VERTCRS["N2000 height",VDATUM["N2000",ID["EPSG",1030]],CS[vertical,1,ID["EPSG",6499]],AXIS["Gravity-related height (H)",up],LENGTHUNIT["metre",1,ID["EPSG",9001]],ID["EPSG",3900]]],TARGETCRS[VERTCRS["EVRF2019 height",VDATUM["European Vertical Reference Frame 2019",ID["EPSG",1274]],CS[vertical,1,ID["EPSG",6499]],AXIS["Gravity-related height (H)",up],LENGTHUNIT["metre",1,ID["EPSG",9001]],ID["EPSG",9389]]],METHOD["Vertical Offset by Grid Interpolation (asc)",ID["EPSG",1085]],PARAMETERFILE["Vertical offset file","fi_2019z.asc",ID["EPSG",8732]],PARAMETER["EPSG code for Interpolation CRS",4258,ID["EPSG",1048]],OPERATIONACCURACY[0.004],ID["EPSG",9573]]'
ct_obj = Transformer.from_pipeline(wkt_9573)
```

Outputs:
```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pyproj/transformer.py", line 675, in from_pipeline
    return Transformer(TransformerFromPipeline(cstrencode(proj_pipeline)))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyproj/transformer.py", line 337, in __init__
    self._local.transformer = transformer_maker()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyproj/transformer.py", line 134, in __call__
    return _Transformer.from_pipeline(self.proj_pipeline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyproj/_transformer.pyx", line 633, in pyproj._transformer._Transformer.from_pipeline
  File "pyproj/_transformer.pyx", line 359, in pyproj._transformer._Transformer._initialize_from_projobj
pyproj.exceptions.ProjError: Input is not a transformation.
```

#### Ex.2 Create a instance of the ``Transformer`` class by using authority code

```python
from pyproj import Transformer
Transformer.from_pipeline("EPSG:9573")
```

Outputs:
```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pyproj/transformer.py", line 675, in from_pipeline
    return Transformer(TransformerFromPipeline(cstrencode(proj_pipeline)))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyproj/transformer.py", line 337, in __init__
    self._local.transformer = transformer_maker()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyproj/transformer.py", line 134, in __call__
    return _Transformer.from_pipeline(self.proj_pipeline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyproj/_transformer.pyx", line 633, in pyproj._transformer._Transformer.from_pipeline
  File "pyproj/_transformer.pyx", line 359, in pyproj._transformer._Transformer._initialize_from_projobj
pyproj.exceptions.ProjError: Input is not a transformation.

```

### Problem description
``Proj`` fails to create a transformation object for the vertical transformation [N2000 height to EVRF2019 height (1) (EPSG:9573)](https://epsg.org/transformation_9573/N2000-height-to-EVRF2019-height-1.html?sessionkey=tb20oafw3g), which transforms [N2000 height](https://epsg.org/crs_3900/N2000-height.html) to [EVRF2019 height](https://epsg.org/crs_9389/EVRF2019-height.html).

### Environment Information
pyproj version 3.6.1
python 3.11

### Installation method
 pip wheel

**Comment by phaarnes** [comment]
An [issue](https://github.com/pyproj4/pyproj/issues/1463) is created in Pyproj GitHub repo.
