### ISSUE TITLE
TransformerGroup does not handle cases where both the allow_superseded and always_xy user arguments is used

### ISSUE THREAD

**Issue by phaarnes** [OSGeo/proj.4#4343]
#### Ex. 1 TransformerGroup fails to list up available transformations when specifying both ``always_xy`` and ``allow_superseded ``

```python
from pyproj.transformer import TransformerGroup
TransformerGroup("EPSG:4230", "EPSG:4326", allow_superseded=True, always_xy=True).transformers
```

Outputs:
```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pyproj/transformer.py", line 207, in __init__
    super().__init__(
  File "pyproj/_transformer.pyx", line 241, in pyproj._transformer._TransformerGroup.__init__
  File "pyproj/_transformer.pyx", line 602, in pyproj._transformer._Transformer._from_pj
  File "pyproj/_transformer.pyx", line 653, in pyproj._transformer._Transformer._init_from_crs
  File "pyproj/_transformer.pyx", line 359, in pyproj._transformer._Transformer._initialize_from_projobj
pyproj.exceptions.ProjError: Input is not a transformation.
```

#### Ex.2 TransformerGroup should return ``36`` available transformations when  ``allow_superseded `` not defined
```python
ct_lst = TransformerGroup("EPSG:4230", "EPSG:4326").transformers
print(len(ct_lst))
```

Outputs:
```python
36
```

#### Ex.3 TransformerGroup should return ``37`` available transformations when ``allow_superseded `` is set to ``True``
```python
ct_lst = TransformerGroup("EPSG:4230", "EPSG:4326", allow_superseded=True).transformers
print(len(ct_lst))
```

Outputs:
```python
37
```

ct_lst = TransformerGroup("EPSG:4230", "EPSG:4326", allow_superseded=True).transformers
print(len(ct_lst))

### Problem description
``TransformerGroup``  fails to a create a list of all available transformation objects when the user set both ``always_xy`` and ``allow_superseded `` equals ``True``. 

### Environment Information
pyproj version 3.6.1
python 3.11

### Installation method
 pip wheel

**Comment by phaarnes** [comment]
An [issue](https://github.com/pyproj4/pyproj/issues/1464) is created in PyProj GitHub repo.

**Comment by rouault** [comment]
This feels more like a pyproj bug, than a PROJ one. At least the exception comes from https://github.com/pyproj4/pyproj/blob/42aa92f489bd266749a44cb78101eae28e20f5c3/pyproj/_transformer.pyx#L341

**Comment by phaarnes** [comment]
Hi Even, 
I see. Feel free to delete this issue if you think its only related to pyproj

**Comment by snowman2** [comment]
I did some debugging and this is what I found:

- `allow_superseded` calls `proj_operation_factory_context_set_discard_superseded` and creates a `PJ` object for `ED50 to WGS 84 (15)` with the `PJ_TYPE_TRANSFORMATION` when calling `proj_create_operations`.
- Combining `allow_superseded` with `always_xy` causes an issue because the `PJ` object is `PJ_TYPE_TRANSFORMATION`. Due to this `proj_coordoperation_is_instantiable` returns True.  However, `proj_normalize_for_visualization` returns a `PJ` object of type `PJ_TYPE_CONCATENATED_OPERATION` for `ED50 to WGS 84 (15)`. This is the source of the error when attempting to create the `Transformer`.

```python
from pyproj import Transformer

print(Transformer.from_pipeline("ED50 to WGS 84 (15)").description)
```
```
"ED50 to WGS 84 (15)"
```
I modified the pyproj code to run `proj_normalize_for_visualization` on `ED50 to WGS 84 (15)` (cannot do this normally with the current release):
```python
from pyproj._transformer import _Transformer

_Transformer.from_pipeline("ED50 to WGS 84 (15)", always_xy=True)
```
```
...
pyproj.exceptions.ProjError: Input is not a transformation.
```
This produces the error above.

@rouault is it expected for `proj_normalize_for_visualization`  convert a `PJ_TYPE_TRANSFORMATION` into `PJ_TYPE_CONCATENATED_OPERATION`?

**Comment by phaarnes** [comment]
Hi @rouault,  @snowman2 

Has this been investigated further? Any conclusion on where the issue resides?

**Comment by rouault** [comment]
> is it expected for `proj_normalize_for_visualization` convert a `PJ_TYPE_TRANSFORMATION` into `PJ_TYPE_CONCATENATED_OPERATION`?

@snowman2 yes, that's exactly how the implementation works: it takes the original transformation and prepends / appends axis swap operations to it where needed, and returns a concatenated operation

**Comment by snowman2** [comment]
> yes, that's exactly how the implementation works: it takes the original transformation and prepends / appends axis swap operations to it where needed, and returns a concatenated operation

Thank you for clarifying that. That sounds like it is not the issue.

To further debug the issue, I ran `proj_coordoperation_is_instantiable` on the `PJ *` object after calling `proj_normalize_for_visualization ` and it raised the error: `missing required input`. Is it expected that a `PJ *` that was instantiable before calling `proj_normalize_for_visualization` to no longer be instantiable after?

**Comment by rouault** [comment]
> and it raised the error: `missing required input`

proj_coordoperation_is_instantiable() returns that error if the passed PJ* object is NULL.

**Comment by snowman2** [comment]
> > and it raised the error: `missing required input`
> 
> proj_coordoperation_is_instantiable() returns that error if the passed PJ* object is NULL.

Huh, you're correct. `proj_normalize_for_visualization ` is returning NULL now. I wonder what version of PROJ I was using that returned a `PJ_TYPE_CONCATENATED_OPERATION` 🤔.

**Comment by phaarnes** [comment]
Hi @rouault and @snowman2,

I have investigated this further, and the root cause seems to be that Pyproj and ``TransformerGroup`` does not properly handle cases where `proj_normalize_for_visualization()` returns NULL.

One example that triggers this issue is the superseded transformation [EPSG:8047](https://epsg.org/concatenated-operation_8047/ED50-to-WGS-84-15.html?sessionkey=w0balagpl1). The issue raise when ``allow_superseeded==True`` in combinateion with ``always_xy=True``. This is a concatenated coordinate operation where the sub-operations have non-overlapping validity areas:

- [EPSG:1147 (ED50→ED87) - Norway N65 area](https://epsg.org/transformation_1147/ED50-to-ED87-2.html?sessionkey=qdvcdc3xyc)
- [EPSG:1146 (ED87→WGS84) - North Sea area](https://epsg.org/transformation_1146/ED87-to-WGS-84-1.html?sessionkey=w8gxl5skml) 

These don't have a common geographic intersection (see extents in the links above), which causes `proj_normalize_for_visualization()` to return NULL.

**On the pyproj side:** 

The crash was caused by pyproj not checking for NULL return from proj_normalize_for_visualization(). The code proceeded to use/destroy an invalid pointer. I have a possible fix ready that:

1. Properly checks for NULL return from proj_normalize_for_visualization()
2. Adds operations that cannot be normalized to unavailable_operations instead of crashing
3. Preserves the original pointer so it can still be used to create a CoordinateOperation


I can make a PR to Pyproj main, so it can be reviewed. 

### Questions/suggestions for PROJ

My interpretation is that the NULL return from `proj_normalize_for_visualization()` for certain coordinate operations (like `ConcatenatedOperation`s with non-overlapping step extents) is **expected behavior** rather than a bug. However, I have a few suggestions for consideration:

1. **Add a `checkExtent` parameter to `proj_normalize_for_visualization()`?**
   
   Currently the C API doesn't allow callers to bypass the extent check. Adding an optional parameter could help:
   ```c
   // Current API
   PJ *proj_normalize_for_visualization(PJ_CONTEXT *ctx, const PJ *obj);
   
   // Possible new API (backward compatible via default value)
   PJ *proj_normalize_for_visualization_ex(PJ_CONTEXT *ctx, const PJ *obj, int check_extent);
   ```
   
   This would allow callers to explicitly opt out of the extent validation when they know the operation is valid despite non-overlapping sub-operation extents.

2. **Skip extent validation for axis-swap wrappers?**
   
   The axis-swap operations added by `normalizeForVisualization()` don't change the geographic validity of the underlying operation. Perhaps the extent check could be skipped specifically when wrapping with axis swaps, since they're purely coordinate order changes with no spatial effect.

3. **Improve error reporting?**
   
   When `proj_normalize_for_visualization()` returns NULL, it would be helpful if the PROJ log/error system provided a clear message explaining *why* (e.g., "Cannot normalize: sub-operation extents do not intersect"). This would help downstream libraries like pyproj provide better diagnostics to users.


I will create a new “enhancement” issue for this topic. I think this issue in the PROJ repository can be closed, as it is not a PROJ “bug” per se.

**Comment by phaarnes** [comment]
The new issue #4631

**Comment by phaarnes** [comment]
@rouault @snowman2 
I have created a PR with a fix according to options 2 outlined above:
#4632
